### ISSUE TITLE
Card Location Data

### ISSUE THREAD

**Issue by j-e-b** [cop4934-fall19-group32/Project-32#17] opened 2019-11-11 03:35 UTC
- [ ] Create a way to represent the location for every card on the puzzle board.
   - [ ] Locations include the card hand and card slot indices.
   - [ ] Considers what card is at which location.
   - [ ] Should be serializable.

**Comment by MrLever** [comment] 2019-12-14 19:33
@j-e-b Is this issue overshadowed by (or should it be merged into) #15

**Comment by MrLever** [comment] 2020-01-14 17:49
Duplicate of #15

**Closed by MrLever** 2020-01-14 17:49 UTC
Labels: Priority:Low, Puzzles
