### ISSUE TITLE
Level Generation v1

### ISSUE THREAD

**Issue by j-e-b** [cop4934-fall19-group32/Project-32#2] opened 2019-11-03 01:45 UTC
## Scripting
Level Generation should make use of the following scripts:
- LevelData.cs
- LevelManager.cs
- GameManager.cs

### LevelData
Contains the following information:
- [x] Number of register cards.
- [x] Numbers of stack cards.
- [x] Number of queue cards.
- [x] Number of heap cards.

### LevelManager
- [x] Instantiates Game Objects based on the information in it's LevelData object.
    - [x] n number of Register Game Objects are instantiated, where n = number of register cards
    - [x] n number of Stack Game Objects are instantiated, where n = number of stack cards
    - [x] n number of Queue Game Objects are instantiated, where n = number of queue cards
    - [x] n number of Heap Game Objects are instantiated, where n = number of heap cards
- [x] Initializes LevelData object using serialized JSON data associated to the current level (specified in GameManager.cs).

### Game Manager
- [x] Contains the current level ID.
- [x] Initializes the game by using the LevelManager script to setup the current level's scene.

## Unity

- [x] Create some basic Game Object prefabs with filler sprite images:
   - Register
   - Stack
   - Queue
   - Heap

- [x] Instantiate GameObject and named GameManager.

- [x] Link GameManager Game Object with the scripts:
   - LevelManager.cs
   - GameManager.cs

- [x] Now associate prefabs with LevelManager members:
   - Link Register prefab with LevelManger Register Game Object.
   - Link Stack prefab with LevelManger Stack Game Object.
   - Link Queue prefab with LevelManger Queue Game Object.
   - Link Heap prefab with LevelManger Heap Game Object.

## Extras
- [ ]  Replace uses of "level" with "puzzle".

**Comment by MrLever** [comment] 2019-11-03 18:12
Duplicate of #1?

**Comment by j-e-b** [comment] 2019-11-03 18:58
I guess this is more of an evolution of #1, since I the means of level deserialization does not require a JSON schema if we serialize levels ourselves initially.

**Closed** 2019-11-10 02:38 UTC
Labels: Puzzles
